inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Unable to set executable bit on windows.
Lint/ScriptPermission:
  Enabled: false
