defaults: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  signing_key: <%= ENV["SIGNING_KEY"] %>
  mailjet:
    api_key: <%= ENV['MAILJET_API_KEY'] %>
    secret_key: <%= ENV['MAILJET_SECRET_KEY'] %>
  sendinblue:
    username: <%= ENV['SENDINBLUE_USER_NAME'] %>
    smtp_key: <%= ENV['SENDINBLUE_SMTP_KEY'] %>

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults

